### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Keeo** [abacao/Boot2Kodi#1]
Hello, thank you for script. 

Could you include original kodi repository to get newest version?
```shell
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update
sudo apt-get install kodi
```

**Comment by abacao** [comment]
Hi,

There is a new branch with the Kodi Repo.
I will need to test it further.
Feel free to use and please get back to me with feedback.

**Comment by abacao** [comment]
It was merged!
