### ISSUE TITLE
Screen not waking up

### ISSUE THREAD

**Issue by vocalico** [abacao/Boot2Kodi#10]
Thanks for your work! It's pretty awesome to have a quick and light install of Kodi with Ubuntu Server.

I have the server always on, and it's connectec to a TV. When I go to the TV, the video signal from the server is off, sometimes it comes back just pressing some keys, but usually it doesn't and is necessary to start playing something through Chorus to wake up the screen. 

Is there any way to disable the screen sleep function? I think it is not related to Kodi because all the Save Power settings are turned off.

**Comment by abacao** [comment]
Hi,

Have you follow the instructions?

Please detail your hardware and software as much as possible.

1. Is the TV connected by HDMI?
2. Please tell me all the steps I need to reproduce the issue and try to be as detailed as possible.

**Comment by vocalico** [comment]
1.- Sort of. The server only has DVI output so it’s connected through a DVI to HDMI cable.

2.- Turn on the server and do nothing with it for some hours. When I do that and come back to play something in kodi I have no video signal until I start playing something, sometimes I even need to start playing a video several times to make it wake up.

**Comment by abacao** [comment]
Hello @vocalico 
Is this still an issue?

**Comment by vocalico** [comment]
Stopped using the server video output, the speakers I used with it got broken so I lost audio. I installed jellyfin and cast the contents to a TV.
