### ISSUE TITLE
can't work on orangep pi pc2

### ISSUE THREAD

**Issue by centralhardware** [abacao/Boot2Kodi#11]
`E: Package 'xserver-xorg-video-intel' has no installation candidate`

**Comment by abacao** [comment]
Hello @centralhardware 

Can you provide more detail?
What OS are you using in the that hardware?
Can you please provide a link for that specif hardware?
I do not own an OrangePi, so all the help will be based on assumptions.

**Comment by centralhardware** [comment]
I googled and on the Internet they write that this single-board player does not support kodi, in principle
