### ISSUE TITLE
Could not open webUI

### ISSUE THREAD

**Issue by ApocKira** [abacao/Boot2Kodi#18]
I do not know if this could find you well.
But I am having a trouble to open the webui from a computer under same ip.
After I start kodi service, I could not access to webui even if I change the /home/kodi/.kodi/userdata/guisettings.xml
<esallinterfaces>true</esallinterfaces>
<webserver>true</webserver>
<webserverpassword></webserverpassword>
<webserverusername></webserverusername>
<zeroconf>true</zeroconf>

it is sill not working. and refused me to connect.

Any support on this one?

**Comment by abacao** [comment]
Hello,

I need more details.

What do you mean by webui? 
What OS are you using, versions, hardware, etc...
Any screenshots can also help.

**Comment by ApocKira** [comment]
I am using Ubuntu 22.04 server. Webui is for me to control kodi. 
Hardware is 
CPU i5 12600k
Mother board asus prime z790m plus
32gb memory

**Comment by abacao** [comment]
I will need to check as I didn't test it beyond 21.04.

Does the issue remains?

**Comment by abacao** [comment]
@ApocKira I was able to test it on 22.04 and didn't had any issues. 
Does the issue remains?
