### ISSUE TITLE
Support system poweroff via UI

### ISSUE THREAD

**Issue by chrisyokum** [abacao/Boot2Kodi#3]
1) Install upower
```
$ apt-get install upower
```
2) Create file /etc/polkit-1/localauthority/50-local.d/custom-actions.pkla with content:
```
[Actions for kodi user]
Identity=unix-user:kodi
Action=org.freedesktop.upower.*;org.freedesktop.consolekit.system.*;org.freedesktop.udisks.*;org.freedesktop.login1.*
ResultAny=yes
ResultInactive=yes
ResultActive=yes
```

This has been verified to work on Ubuntu Server 18.04.1 LTS, just needs to be added to this setup process.

**Comment by chrisyokum** [comment]
Thanks for the script, btw. It worked perfectly to get started on 18.04!

**Comment by abacao** [comment]
Glad to hear that. I will check as soon as possible and try to add this code to the script.

**Comment by abacao** [comment]
Feature checked and built in. Thank you.
If you have any other suggestions, feel free to discuss them.
