### ISSUE TITLE
Comment accéder à Kodi une fois installé ?

### ISSUE THREAD

**Issue by Oss09** [abacao/Boot2Kodi#6]
Bonjour,

Je viens de suivre tes instructions d'installations. Mais je ne trouve pas comment accéder à Kodi une fois l'installation effectué ?

Merci

**Comment by abacao** [comment]
Hi, I don't speak French.

Using Google to translate, my answer is: reboot

**Comment by abacao** [comment]
The answer to the issue is reaching the 30 days mark. It will be closed on that date.
