### ISSUE TITLE
Unnecessary packages?

### ISSUE THREAD

**Issue by radusuciu** [abacao/Boot2Kodi#8]
Hi,

I'm wondering if these packages are needed:
- upower
- xserver-xorg-video-intel

upower seems to only be useful on battery powered system whereas xserver-xorg-video-intel isn't needed except on systems running intel integrated graphics. I should mention that I installed this on a system that only has an ATI GPU, and things seem to work despite not having xserver-xorg-video-radeon.

**Comment by abacao** [comment]
Hello,

Yes they are. This installation process has the goal to help the largest number of people but you will find why they are used below.

upower was necessary to be able to use the power menu option inside Kodi
https://github.com/abacao/Boot2Kodi/commit/db0e409d7974f41692c266b77c3554a373d6facd

About the intel drivers: is the most frequent GPU. If you don't know, the Linux Kernel already has drivers for the ATI AMD GPU.

**Comment by radusuciu** [comment]
Thank you for explaining!
