### ISSUE TITLE
SMB from GUI

### ISSUE THREAD

**Issue by sebaxakerhtc** [abacao/Boot2Kodi#9]
Hi!
It's very useful. Thank you!
I'm looking for it as alternative for Libreelec with full functional of ubuntu( For LAMP, Nextcloud, etc)
SMB service from Kodi interface switched ON, but I can't to connect to it from another computer (Win, Mac)

If it helps... I think it's a good idea to make default folders in home dir with write permitions(now i cant make new dir from kodi file manager), like Videos, Downloads, Music, etc and "switching on" SMB from kodi make home dir shared.

**Comment by abacao** [comment]
Hello,
SMB Service is a service that not everyone will use but feel free to open a pull-request with the changes you are suggesting and I will take a look.
